### ISSUE TITLE
Easier log tailing commands

### ISSUE THREAD

**Issue by recursivefunk** [istrategylabs/mo-cli#2]
Since mo-django and mo-node have a `mo.yml` file which has their app name for heroku staging and prod, it would be nice if the cli used this file to make certain command easier. For instance, if I have an app `client-super-app-grandstand`, in order to tail the logs in production I have to type

`heroku logs --tail --app client-super-app-grandstand`

And for staging 

`heroku logs --tail --app client-super-app-grandstand-staging`

It would be nice if I could just (from anywhere in a mo project)

`mo logs` => tail prod
`mo logs -s` => tail staging

**Comment by jcarbaugh** [comment]
👍 x 100
